### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by charlie17** [nuxtclub/supabase#1]
Came across this and it's very helpful - thanks! A couple things:

1. Seems it is not necessary to install [Nuxt Auth](https://auth.nuxtjs.org/) or even to setup Vuex in Nuxt for this to work? I was pleasantly surprised to see that, just using this, login seems to persist across pages and even if I close and reopen the browser. Do I have that right - this runs independently from Nuxt Auth (apart from using Middleware) and no store is necessary?

2. In your fetching data example it says `middleware: 'auth',` but I think you may have intended `middleware: 'authenticated',` to match what follows

**Comment by imlautaro** [comment]
> 
> 
> Came across this and it's very helpful - thanks! A couple things:
> 
>     1. Seems it is not necessary to install [Nuxt Auth](https://auth.nuxtjs.org/) or even to setup Vuex in Nuxt for this to work? I was pleasantly surprised to see that, just using this, login seems to persist across pages and even if I close and reopen the browser. Do I have that right - this runs independently from Nuxt Auth (apart from using Middleware) and no store is necessary?
> 
>     2. In your fetching data example it says `middleware: 'auth',` but I think you may have intended `middleware: 'authenticated',` to match what follows

1. Yes, you can use the module without Nuxt Auth. The authentication is already solved in the supabase client for javascript, this module only does what is necessary to make it work in Nuxt in the easiest way possible.
2. Exactly, thank you very much for notifying me 💚
