### ISSUE TITLE
Import to js file

### ISSUE THREAD

**Issue by charlie17** [nuxtclub/supabase#2]
A basic thing, but how to access `$supabase` from a non-Vue file? Trying to use within a Pinia store file (.js). Getting `$supabase is not defined`. Tried including `import { $supabase } from "@nuxtclub/supabase";` but that shows `export '$supabase' was not found in '@nuxtclub/supabase'`

Thanks

**Comment by imlautaro** [comment]
That's because the $supabase object is injected in the nuxt context. You should use the context to access to the $supabase object.

If you're using composition api, you can say something like `const { $supabase } = useContext()`.

**Comment by skwasan** [comment]
@imlautaro How ot do this? could you give example?

**Comment by imlautaro** [comment]
> @imlautaro How ot do this? could you give example?

Are you using Composition API?
